fos_user:
    db_driver: orm
    firewall_name: main
    user_class: WS\UserBundle\Entity\User
    service:
        user_manager: pugx_user_manager
    registration:
        form:
            type: WS\UserBundle\Form\RegistrationType

pugx_multi_user:
  users:
    admin:
        entity:
          class: WS\UserBundle\Entity\Admin
        registration:
          form:
            type: WS\UserBundle\Form\Type\RegistrationAdminFormType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: WSAdminBundle:Administrateur:index.html.twig
        profile:
          form:
            type: WS\UserBundle\Form\Type\ProfileAdminFormType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    freelancer:
        entity: 
          class: WS\UserBundle\Entity\Freelancer
        registration:
          form: 
            type: WS\UserBundle\Form\Type\RegistrationFreelancerFormType
          template: WSUserBundle:Registration:freelancer.form.html.twig
        profile:
          form:
            type: WS\UserBundle\Form\Type\ProfileFreelancerFormType
    client:
        entity: 
          class: WS\UserBundle\Entity\Client
        registration:
          form: 
            type: WS\UserBundle\Form\Type\RegistrationClientFormType
          template: WSUserBundle:Registration:client.form.html.twig
        profile:
          form: 
            type: WS\UserBundle\Form\Type\ProfileClientFormType