freelancer_registration:
    path:  /register/freelancer
    defaults: { _controller: WSUserBundle:RegistrationFreelancer:register }

client_registration:
    path:  /register/client
    defaults: { _controller: WSUserBundle:RegistrationClient:register }
