services:
#    ws_user.example:
#        class: WS\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    acme.twig.country_extension:
        class: WS\UserBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }

    ws_user.login:
        class: WS\UserBundle\Service\Login
        arguments: [@request, @security.csrf.token_manager]
        scope: request