<?php

namespace WS\ServiceBundle\Repository;

/**
 * FreelancePostuleMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreelancePostuleProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
