<?php

namespace WS\ServiceBundle\Repository;

/**
 * DonateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllMissionByDomainAndCountry($idDomain, $codeCountry) {

        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT m
            FROM WSServiceBundle:Mission m
            INNER JOIN m.domains d
            WHERE d.id = :idDomain 
              AND m.country = :codeCountry 
              AND m.validate = 1 
              AND m.open = 1 
              ORDER BY m.dateCreation DESC 
        ')->setParameters( array (
            'idDomain' => $idDomain,
            'codeCountry' => $codeCountry
        ));

        return $query->getResult();
    }
}
