<?php

namespace WS\ServiceBundle\Repository;

/**
 * MissionSolicitFreelanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionSolicitFreelanceRepository extends \Doctrine\ORM\EntityRepository
{
}
