<?php

namespace WS\ServiceBundle\Repository;

/**
 * DonateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllProjectByDomainAndCountry($idDomain, $codeCountry, $idFreelance) {

        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT m
            FROM WSServiceBundle:Project m
            INNER JOIN m.domains d
            WHERE d.id = :idDomain 
              AND m.country = :codeCountry 
              AND m.validate = 1 
              AND m.open = 1 
              AND m.id NOT IN (
                SELECT mi.id 
                FROM WSServiceBundle:FreelancePostuleProject fpp
                JOIN fpp.projet mi
                JOIN fpp.freelancer f 
                WHERE f.id = :idFreelance
              )
            ORDER BY m.dateCreation DESC 
        ')->setParameters( array (
            'idDomain' => $idDomain,
            'codeCountry' => $codeCountry,
            'idFreelance' => $idFreelance
        ));

        return $query->getResult();
    }
}
