<?php

namespace WS\ServiceBundle\Repository;

/**
 * RequestServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
