<?php

namespace WS\UserBundle\Repository;

/**
 * CompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllCompetenceByUser($idUser) {

        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT c.id as id, c.libel as libelle, c.nbAnneeExp as nbae
            FROM WSUserBundle:Competence c
            JOIN c.freelancer f
            WHERE f.id = :idUser
        ')->setParameters( array (
            'idUser' => $idUser
        ));

        return $query->getResult();
    }
}
