<?php

namespace WS\UserBundle\Repository;

/**
 * DomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllDomain() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT d.id as idDomain, d.libel as libelleDomain, c.id as idCategory, c.libelle as libelleCategory
            FROM WSUserBundle:Domain d
            JOIN d.category c
        ');

        return $query->getResult();
    }

    public function findAllDomainByCategory($idCategory) {

        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT d.id, d.libel
            FROM WSUserBundle:Domain d
            JOIN d.category c
            WHERE c.id = :idCategory
        ')->setParameters( array (
            'idCategory' => $idCategory
        ));

        return $query->getResult();
    }

    public function findAllDomainByUser($idUser) {

        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT d.id as id, d.libel as libelle_domain, c.libelle as libelle_categorie
            FROM WSUserBundle:Freelancer f
            INNER JOIN f.domains d
            JOIN d.category c
            WHERE f.id = :idUser
        ')->setParameters( array (
            'idUser' => $idUser
        ));

        return $query->getResult();
    }
}
