<?php

namespace WS\UserBundle\Repository;

/**
 * RealizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealizationRepository extends \Doctrine\ORM\EntityRepository
{
}
