ws_core_homepage:
    path:     /
    defaults: { _controller: WSCoreBundle:Core:index }

ws_core_about:
    path:     /about
    defaults: { _controller: WSCoreBundle:Core:about }

ws_core_contact:
    path:     /contact
    defaults: { _controller: WSCoreBundle:Core:contact }

ws_core_how_to:
    path:     /how-to
    defaults: { _controller: WSCoreBundle:Core:howto }

# Register Mission
ws_mission_create_index:
    path:     /mission/create
    defaults: { _controller: WSCoreBundle:Mission:index }

ws_mission_delete:
    path:     /mission/delete/{id}
    defaults: { _controller: WSCoreBundle:Mission:delete }

ws_mission_update:
    path:     /mission/update/{id}
    defaults: { _controller: WSCoreBundle:Mission:update }

ws_mission_open_or_close:
    path:     /mission/open_or_close/{id}/{val}
    defaults: { _controller: WSCoreBundle:Mission:openOrClose }

ws_mission_valid_or_not:
    path:     /mission/valid_or_not/{id}/{val}
    defaults: { _controller: WSCoreBundle:Mission:validOrNot }

ws_mission_all_domains:
    path:     /create/mission/alldomains
    defaults: { _controller: WSCoreBundle:Mission:allDomains }
    options:
        expose: true

# Results Search
ws_core_result_freelance:
    path:     /result/freelances
    defaults: { _controller: WSCoreBundle:Core:resultFreelance }

ws_core_result_mission:
    path:     /result/missions
    defaults: { _controller: WSCoreBundle:Core:resultMission }

# Find freelance by domain
ws_core_find_freelance_by_domain:
    path:     /domain/{id}/freelances
    defaults: { _controller: WSCoreBundle:Core:findFreelance }

# Postule Mission
ws_core_postule_mission:
    path:     /postule/mission/{id}
    defaults: { _controller: WSCoreBundle:Core:postuleMission }
    options:
        expose: true