services:
#    ws_core.example:
#        class: WS\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    pambe.twig.customfilter_extension:
        class: WS\CoreBundle\Twig\CustomFilterExtension
        tags:
            - { name: twig.extension }